export const allQuests = [
  {
    id: 'greeting',
    profile: 'human',
    type: 'text',
    text: () =>
      `Hey! We're going to ask you a few questions about your dog(s) so we can curate supplements personalized just for them! <br/><br/> Let's get started. What's your name?`,
    answer: null,
  },
  {
    id: 'count',
    profile: 'human',
    type: 'text',
    referQuestForText: 'greeting',
    text: name => `Nice to meet you ${name}! How many dogs do you have?`,
    answer: null,
  },
  {
    id: 'dogName',
    profile: 'human',
    type: 'text',
    text: () => 'What is your dog name?',
    answer: null,
  },
  {
    id: 'gender',
    profile: 'pet',
    type: 'singleSelect',
    referQuestForText: 'dogName',
    text: name => `What is ${name}'s gender?`,
    options: [{ key: 'girl', title: 'Girl', type: 'text' }, { key: 'boy', title: 'Boy', type: 'text' }],
    answer: null,
  },
  {
    id: 'reproducibility',
    profile: 'pet',
    type: 'singleSelect',
    referQuestForText: 'dogName',
    text: name => `${name} is`,
    options: [
      {
        key: 'spayed',
        title: 'Spayed',
      },
      {
        key: 'notSpayed',
        title: 'Not Spayed',
      },
    ],
    answer: null,
  },
  {
    id: 'activity',
    profile: 'pet',
    type: 'singleSelect',
    referQuestForText: 'dogName',
    text: name => `How active would you say ${name} is?`,
    options: [
      {
        key: 'couchPotato',
        title: 'Couch Potato',
        type: 'text',
        description: 'She enjoys a long snooze over a run at the park',
      },
      {
        key: 'moderate',
        title: 'Moderate',
        type: 'text',
        description: 'She gets some good exercise about 3x a week',
      },
    ],
    answer: null,
  },
  {
    id: 'photo',
    profile: 'pet',
    type: 'image',
    url: 'assets/images/puppy.jpg',
  },
  {
    id: 'notification',
    profile: 'pet',
    type: 'notification',
    text: () => 'Aww a lazy pup! Almost done now moving on to the details.',
  },
  {
    id: 'allergy',
    profile: 'pet',
    type: 'singleSelect',
    referQuestForText: 'dogName',
    text: name => `Does ${name} have any allergies?`,
    options: [
      {
        key: 'yes',
        title: 'Yes',
        type: 'text',
      },
      {
        key: 'no',
        title: 'No',
        type: 'text',
      },
    ],
    answer: null,
  },
  {
    id: 'allergyTypes',
    profile: 'pet',
    type: 'multiSelect',
    referQuestForText: 'dogName',
    referUse: 'allergy',
    text: name => `Poor.${name}! Select her known allergies.`,
    options: [
      { key: 'allergy1', title: 'Allergy' },
      { key: 'allergy2', title: 'Allergy' },
      { key: 'allergy3', title: 'Allergy' },
      { key: 'allergy4', title: 'Allergy' },
      { key: 'allergy5', title: 'Allergy' },
      { key: 'allergy6', title: 'Allergy' },
      { key: 'allergy7', title: 'Allergy' },
      { key: 'allergy8', title: 'Allergy' },
    ],
    answer: [],
  },
]
